---
- name: Extract mysql root password
  command: /bin/hiera -c /etc/puppet/hiera.yaml mysql::server::root_password
  register: mysql_root_password
  become: true
  changed_when: false
  

- name: Execute mysql backup 
  shell: podman exec mysql bash -c "mysqldump -uroot -p{{mysql_root_password.stdout}} --opt --all-databases" > {{ backup_dir.path }}/undercloud-all-databases.sql
  become: true
