---
- name: Check tmp directory exists 
  stat:
    path: "{{osp16_undercloud_backup_tmp_dir}}"
  register: check_tmp_dir

- name: Fail if tmp director doesn't exists
  fail:
    msg: "{{osp16_undercloud_backup_tmp_dir}} doesn't exists or isn't a directory"
  when: ( not check_tmp_dir.stat.exists ) or ( not check_tmp_dir.stat.isdir )


- name: Create backup directory
  file:
    path: "{{osp16_undercloud_backup_tmp_dir}}/{{osp16_undercloud_backup_destination_filename_format}}"
    state: directory
    mode: '0755'
  register: backup_dir
